# Generated by Django 4.0.7 on 2023-06-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_config_model',
            name='Router_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Int_cross', to='interfaces.router_model'),
        ),
        migrations.AlterField(
            model_name='interface_model',
            name='Router_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.router_model'),
        ),
    ]
