# Generated by Django 4.0.7 on 2023-06-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Showrun', models.CharField(max_length=5000)),
                ('Filedate', models.DateField()),
            ],
        ),
    ]
