# Generated by Django 4.0.7 on 2023-06-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RouterConfig',
            new_name='RouterConfig_model',
        ),
    ]
