# Generated by Django 4.0.7 on 2023-06-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0002_rename_routerconfig_routerconfig_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerconfig_model',
            name='IP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routerconfig_model',
            name='Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
