# Generated by Django 4.0.7 on 2023-07-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_routerconfig_model_ip_routerconfig_model_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerconfig_model',
            name='IP',
        ),
        migrations.RemoveField(
            model_name='routerconfig_model',
            name='Type',
        ),
    ]
