# Generated by Django 4.0.7 on 2023-07-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0004_remove_routerconfig_model_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
