# Generated by Django 4.0.7 on 2023-07-12 09:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchPort',
            fields=[
                ('Router', models.CharField(max_length=60)),
                ('Int', models.CharField(max_length=60)),
                ('Peygiri', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999999)])),
                ('Des', models.CharField(max_length=155)),
                ('IP', models.CharField(blank=True, max_length=35, null=True)),
                ('VLAN', models.IntegerField(validators=[django.core.validators.MinValueValidator(2300), django.core.validators.MaxValueValidator(2999)])),
                ('Date', models.DateField()),
                ('Info', models.CharField(blank=True, max_length=25)),
                ('File', models.CharField(max_length=60)),
                ('Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.servicetype')),
                ('Theauthor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdslPort',
            fields=[
                ('Router', models.CharField(max_length=60)),
                ('Newint', models.CharField(max_length=60)),
                ('Encap', models.CharField(max_length=50)),
                ('Peygiri', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999999)])),
                ('Des', models.CharField(max_length=155)),
                ('IP', models.CharField(blank=True, max_length=35, null=True)),
                ('VLAN', models.IntegerField(validators=[django.core.validators.MinValueValidator(2300), django.core.validators.MaxValueValidator(2999)])),
                ('PE', models.CharField(blank=True, max_length=10, null=True)),
                ('Date', models.DateField()),
                ('Dayer', models.BooleanField(default=False)),
                ('Info', models.CharField(blank=True, max_length=25)),
                ('File', models.CharField(max_length=60)),
                ('Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.servicetype')),
                ('Theauthor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
